id: P007853
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14491
  title: དག་ཡིག་ལྷ་ཆབ་འཁྱིལ་བ།
  author: ''
  volumes:
    255b5f4780a54acebd310f0d848a543b:
      image_group_id: I1KG14839
      title: ''
      volume_number: 1
      total_pages: 118
ebook_metadata:
  title: དག་ཡིག་ལྷ་ཆབ་འཁྱིལ་བ།
  author: ''
  sku: P007853
  cover: cover.jpg
  layers:
  - pagination
